### ISSUE TITLE
Search and filter don't work in API reference

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/developer.playcanvas.com#217]
As per title. Nothing happens when tryng to make a search or filter an API property in
https://developer.playcanvas.com/en/api/

**Comment by willeastcott** [comment]
Fixed. Thanks for reporting! 😄

**Comment by Maksims** [comment]
I'm afraid it is still not fixed. [Home page of API Reference](https://developer.playcanvas.com/en/api/) still tries to load interface.js instead of new 3 js files.

**Comment by willeastcott** [comment]
It's not been deployed yet.

**Comment by willeastcott** [comment]
It's deployed now.
